definitions:
  entity.User:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  router.loginResponseBody:
    properties:
      expire:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
  description: API doc for PD Capatain
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ToC PD Capatain
  version: 1.0.0-alpha
paths:
  /-/health:
    get:
      consumes:
      - application/json
      description: healthCheck
      operationId: healthCheck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: healthCheck
      tags:
      - Health
  /login:
    post:
      consumes:
      - application/json
      description: Every api request will extend token expired time, websocket will
        not extend.
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/router.loginResponseBody'
      summary: Login
      tags:
      - Login V1
swagger: "2.0"
